name: Checkout Repository

description: "This action checks out the code from the repository using the \nGitHub Actions 'actions/checkout' action with sparse checkout.\n#magic___^_^___line\n"
inputs:

  paths:
    description: 'A comma-separated list of paths to checkout (e.g., dir1/*, dir2/file.txt). Defaults to all files.'
    required: false
    default: '.'

  image_name:
    description: 'The name of the Docker image to build.'
    required: true

  image_tag:
    description: "tag"
    required: true

runs:
  using: "composite"
  steps:
  - name: Checkout code
    uses: actions/checkout@v4
    with:
      sparse-checkout: ${{ inputs.paths }}

  - name: Build Docker image
    shell: bash
    run: |
      docker build -t=${{ inputs.image_name }}:${{ inputs.image_tag }} .


  - name: Run Trivy vulnerability scanner
    uses: aquasecurity/trivy-action@0.20.0
    with:
       image-ref: '${{ inputs.image_name }}:${{ inputs.image_tag }'
       format: 'sarif'
       output: 'trivy-results.sarif'


