name: Docker Build


on:
  workflow_call:
    inputs:
      image_name:
        description: 'The name of the Docker image'
        required: true
        type: string
      image_tag:
        description: 'The tag for the Docker image'
        required: true
        default: 'latest'
        type: string

jobs:
  DockerBuild:
    name: Build Docker
    runs-on: ubuntu-latest

    steps:
    - name: Build
      uses: welbsterhansi/github-pipeline-template/docker@main
      with:
        image_name: ${{ inputs.image_name }}
        image_tag: ${{ inputs.image_tag }}
