name: Docker CI


on:
  workflow_call:

jobs:
  checkout:
    name: Docker Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: welbsterhansi/github-pipeline-template/docker@main
