name: Docker CI


on:
  workflow_call:

jobs:
  checkout:
    name: Checkout Code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: /templates/common/checkout/action.yaml@main
