name: Docker Build


on:
  workflow_call:

jobs:
  checkout:
    name: checkout
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: welbsterhansi/github-pipeline-template/docker@main
